# Configuration
#
# Replace the following placeholders with the correct values for
# your installation.
#
# <SEARCH_URL>: The URL for performing the search
# <WEBSITE_SEARCH_URL>: The URL for the website search page (with query parameter)

defaults: &defaults
  search_url: <%= ENV['LIBRARY_WEBSITE_SEARCH_SOLR_URL'] %>
  # Query params should be listed in "hash" format
  query_params:
    # The number of results to return
    rows: 3
    # Template for the "q" parameter. SEARCH_TERM will be replaced with the
    # URI escaped search term
    q_template: 'text:SEARCH_TERM'
  loaded_link: 'website?query='
  no_results_link: 'website'

development:
  <<: *defaults

test:
  <<: *defaults

staging:
  <<: *defaults

production:
  <<: *defaults
