# Configuration
#
# Replace the following placeholders with the correct values for
# your installation.
#
# <YOUR_WSKEY>: The "wskey" provided by OCLC
# <YOUR_SECRET>: The "secret" provided by OCLC
# <AUTHENTICATING_INSTITUTION_ID>: The "authenticating institution id" provided
#                                 by OCLC
# <CONTEXT_INSTITUTION_ID>: The "context institution id" provided
#                           by OCLC (typically the same as the institution id)
# <LOADED_LINK>: The base URL to send the query to
# <URL_LINK>: The base URL for result links
# <NO_RESULTS_LINK>: The URL to use when no results are found
# <DOI_LINK>: The base URL to use for retrieving articles with DOIs
defaults: &defaults

  # The following properties should only be defined when the
  # world_cat_discovery_api_seacher is not being used.
  # wskey: <%= ENV['WORLD_CAT_DISCOVERY_API_WSKEY'] %>
  # secret: <%= ENV['WORLD_CAT_DISCOVERY_API_SECRET'] %>
  # authenticatingInstitutionId: <%= ENV['WORLD_CAT_DISCOVERY_API_INSTITUTION_ID'] %>
  # contextInstitutionId: <%= ENV['WORLD_CAT_DISCOVERY_API_INSTITUTION_ID'] %>

  # world_cat_discovery_api_article-specific properties
  loaded_link: "https://umaryland.on.worldcat.org/search?format=Artchap&queryString="
  url_link: "https://umaryland.on.worldcat.org/oclc/"
  no_results_link: "https://umaryland.on.worldcat.org/discovery"
  doi_link: "http://proxy-um.researchport.umd.edu/login?url="

  # Citation Finder URL
  citation_finder_link: https://umaryland.on.worldcat.org/atoztitles/link

  # OpenURL resolver service properties
  open_url_resolver_service_link: https://worldcat.org/webservices/kb/openurl/resolve
  world_cat_open_url_wskey:  <%= ENV['WORLD_CAT_OPEN_URL_RESOLVER_WSKEY'] %>

development:
  <<: *defaults

test:
  <<: *defaults

staging:
  <<: *defaults

production:
  <<: *defaults
