# Configuration
#
# Replace the following placeholders with the correct values for
# your installation.
#
# <YOUR_WSKEY>: The "wskey" provided by OCLC
# <YOUR_SECRET>: The "secret" provided by OCLC
# <AUTHENTICATING_INSTITUTION_ID>: The "authenticating institution id" provided
#                                 by OCLC
# <CONTEXT_INSTITUTION_ID>: The "context institution id" provided
#                           by OCLC (typically the same as the institution id)
# <LOADED_LINK>: The base URL to send the query to
# <URL_LINK>: The base URL for result links
# <NO_RESULTS_LINK>: The URL to use when no results are found

defaults: &defaults
  # The following propreties are common to both searchers. If the
  # world_cat_discovery_api searcher is not being used, copy these
  # properties into the world_cat_discovery_api_article_config.yml file
  wskey: <%= ENV['WORLD_CAT_DISCOVERY_API_WSKEY'] %>
  secret: <%= ENV['WORLD_CAT_DISCOVERY_API_SECRET'] %>
  authenticatingInstitutionId: <%= ENV['WORLD_CAT_DISCOVERY_API_INSTITUTION_ID'] %>
  contextInstitutionId: <%= ENV['WORLD_CAT_DISCOVERY_API_INSTITUTION_ID'] %>

  # world_cat_discovery_api-specific properties
  loaded_link: "https://umaryland.on.worldcat.org/search?queryString="
  url_link: "https://umaryland.on.worldcat.org/oclc/"
  no_results_link: "https://umaryland.on.worldcat.org/discovery"

development:
  <<: *defaults

test:
  <<: *defaults

staging:
  <<: *defaults

production:
  <<: *defaults
